#Problem:Find the difference
#Link:https://leetcode.com/problems/find-the-difference/
#Difficulty:Easy

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

class Solution {
public:
    char findTheDifference(string s, string t) {
        long long sum=0;
        long long difference=0;
        for(char c:t)
        {
            sum+=c-'a';
        }
        for(char c:s)
        {
            difference+=c-'a';
        }
        return char(sum-difference+'a');
    }
};